server:
  port: 8081
spring:
  #  jpa settings
  jpa:
    properties.hibernate.format_sql: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  #  db settings
  datasource:
    platform: postgres
    #    db info sample begin
    url: jdbc:postgresql://localhost:5432/uams
    username: hs
    password: qweqwe
    #    db info sample end
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    sql-script-encoding: utf-8
  # server auto reload
  devtools:
    livereload:
      enabled: false
  freemaker:
    cache: false
