version: "3.3"
services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    # volumes:
    # - ./db/data:/var/lib/postgresql/data
    # - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh # 생성시 실행할 스크립트
    env_file: .env
    environment:
      TZ: Asia/Seoul
    restart: always

  # hs_back:
  #   image: openjdk:11-jdk
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - ./backend/build/libs:/backend
  #   working_dir: /backend
  #   command: java -jar hs_back-0.0.1-SNAPSHOT.jar
  #   depends_on:
  #     - postgresql
  #   links:
  #     - postgresql
  # restart: always

  # hs_front:
  #   image: node:19-alpine
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./frontend:/frontend
  #   working_dir: /frontend
  #   command: npm run serve
  #   depends_on:
  #     - postgresql
  #     - hs_back
  # links:
  #   - hs_back
  # restart: always
